### ISSUE TITLE
Missing facpl2/util source files 

### ISSUE THREAD

**Issue by MiguelR8** [andreamargheri/FACPL#3]
I noticed the `Facpl2Switch` class doesn't have a source file in the repo, and yet it is included in the latest release (2.0.5) under `plugins/it.unifi.xtext.facpl2_1.0.0.201807111101.jar`

In fact, other core classes such as `DateLiteral`, `AttributeReq`, `PAF` and `NotExpression` don't have a source file, all coming from the `it.unifi.xtext.facpl.facpl2` package. Strangely, the `Effect` class _does_ have a source file of its own (`/LIB/FACPL_Library/src/it/unifi/facpl/lib/enums/Effect.java`)

Do you have any pointers to the missing files?

**Comment by andreamargheri** [comment]
Hi @MiguelR8 

the classes you are referring to are generated as part of the compile process of the FACPL language grammar defined with Xtext

The classes are included in the standalone .jar because its aim is to allow you to run the FACPL parsing and java code capabilities without setting up and configuring the whole Xtext project. 

You can find here an overview of the toolchain that was developed for FACPL https://facpl.readthedocs.io/en/latest/txt/intro.html#facpl-at-a-glance

If interested in how Xtext works please refer to this http://www.eclipse.org/Xtext/ 

** Notice that the code was developed and fully tested with these dependencies https://facpl.readthedocs.io/en/latest/txt/install.html#eclipse-installation

**Comment by MiguelR8** [comment]
Hi @andreamargheri 

Thank you. I see now that the grammar is defined in `Facpl2.xtext`, where many of the above mentioned classes are defined.
